### ISSUE TITLE
Two Cantrips and Six 1st Circle spells too many?

### ISSUE THREAD

**Issue by ScottMaclure** [Vladar4/itdr#4]
Was creating some PCs for a one-shot, and I was randomly rolling for cantrips & spells - my feel is that six starting spells plus two cantrips is a lot to begin with.

I think I will give someone who takes Mystic 2x Cantrips and 3x 1st Circle spells to start.

They should find scrolls while adventuring as loot, to expand their tome, etc.

Thoughts?

**Comment by Vladar4** [comment]
Keep in mind that you still can prepare only one spell plus one signature at 1st level. Other 1st level spells will most probably be used in non-combat situations anyway. Considering the d6hp at 1st level, mystic will focus on cantrips, saving the spells for the most dire combat situations.

Sure, you can run it your way as well, just keep in mind that when combined with rolling for spells it will somewhat hinder the mystic on 1st level.

**Comment by ScottMaclure** [comment]
Thanks for the reply!

My thinking was around the "cognitive load" of rolling up a level 1 Mystic PC, you have 8 "spells" to assign.

Hrm, I think I will try RAW first then, and get feedback from players.

Cheers!

**Comment by ScottMaclure** [comment]
FWIW, I'm going to use this page to quickly generate starting cantrips + 1st circle spells:

https://perchance.org/itdr-mystic-spells
